### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space-assets#1]
https://smcameron.github.io/space-nerds-in-space/#multiplayerinstructions in step 2.2 points to this repo: 

> Install any additional art assets you might want to use (for extra solar systems) from https://github.com/smcameron/space-nerds-in-space-assets on all your computers.

This repo states it is obsolete but refers to a dead link:

> NOTE THIS REPO IS OBSOLETE
> 
> Instead, you can run "make update-assets" and download assets that way (more than are in this repo).
> 
> See: https://spacenerdsinspace.com/index.html#additionalassets

**Comment by smcameron** [comment]
Fixed by:

* 723e8ac83701908b052ae0b8d0bb463501ce98e8  Fix broken link to instructions for obtaining additional assets
* [a42943b23f01c5b39f082153e92091b7eb6e1365](https://github.com/smcameron/space-nerds-in-space/commit/a42943b23f01c5b39f082153e92091b7eb6e1365) remove link to obsolete additional art assets repo
